#!/usr/bin/env node
'use strict';

var fs   = require('fs');
var path = require('path');

var ROOT       = __dirname;
var configPath = path.join(ROOT, 'playbrick.config.js');

if (!fs.existsSync(configPath)) {
  console.error('Error: playbrick.config.js not found.');
  console.error('       Copy playbrick.config.js.example → playbrick.config.js and fill in the values.');
  process.exit(1);
}

var config = require(configPath);

if (!config.childTheme) {
  console.error('Error: playbrick.config.js is missing "childTheme".');
  console.error('       Add: childTheme: \'../wp-content/themes/my-child-theme\'');
  process.exit(1);
}

var CHILD_THEME = path.resolve(ROOT, config.childTheme);

// Derive the uploads sub-path from outDir (e.g. "uploads/assets" → "assets").
var assetsSubdir = 'assets';
if (config.outDir) {
  var normalized = config.outDir.replace(/\\/g, '/');
  var match = normalized.match(/wp-content\/uploads\/(.+?)\/?\s*$/);
  if (match) {
    assetsSubdir = match[1];
  } else {
    console.warn('Warning: outDir does not look like a wp-content/uploads/* path.');
    console.warn('         Edit the generated enqueue code manually after setup.');
  }
}

// ── Enqueue snippet (appended to existing file or written to a new one) ───────

var ENQUEUE_HOOK = '\n'
  + '// PlayBrick — dev/prod enqueue. Re-run: pnpm run setup to regenerate.\n'
  + 'add_action( \'wp_enqueue_scripts\', function () {\n'
  + '    $is_dev = ! defined( \'PLAYBRICK_ENV\' ) || PLAYBRICK_ENV === \'dev\';\n'
  + '\n'
  + '    if ( $is_dev ) {\n'
  + '        // Development: serve directly from playbrick/ — no build step needed.\n'
  + '        $base = get_home_url() . \'/playbrick\';\n'
  + '        wp_enqueue_style( \'playbrick\', $base . \'/dev.css\', [], null );\n'
  + '        wp_enqueue_script( \'playbrick\', $base . \'/dev.js\', [], null, true );\n'
  + '    } else {\n'
  + '        // Production: serve minified output from `pnpm run build`.\n'
  + '        $upload = wp_upload_dir();\n'
  + '        $base   = $upload[\'baseurl\'] . \'/' + assetsSubdir + '\';\n'
  + '        wp_enqueue_style( \'playbrick\', $base . \'/style.min.css\', [], null );\n'
  + '        wp_enqueue_script( \'playbrick\', $base . \'/script.min.js\', [], null, true );\n'
  + '    }\n'
  + '} );\n';

// ── Strategy A: append to an existing theme enqueue file ─────────────────────

if (config.enqueueFile) {
  var targetFile = path.resolve(CHILD_THEME, config.enqueueFile);

  if (!fs.existsSync(targetFile)) {
    console.error('Error: enqueueFile not found: ' + targetFile);
    process.exit(1);
  }

  var content = fs.readFileSync(targetFile, 'utf8');

  if (content.includes('playbrick')) {
    console.log('✓  ' + path.relative(ROOT, targetFile) + ' already contains PlayBrick enqueue — nothing to change.');
  } else {
    // Append before closing ?> if present, otherwise just append.
    var trimmed = content.trimEnd();
    if (trimmed.endsWith('?>')) {
      content = trimmed.slice(0, -2).trimEnd() + '\n' + ENQUEUE_HOOK;
    } else {
      content = trimmed + '\n' + ENQUEUE_HOOK;
    }
    fs.writeFileSync(targetFile, content);
    console.log('✓  Appended to: ' + path.relative(ROOT, targetFile));
  }

  done();
  return;
}

// ── Strategy B (default): create a standalone file + patch functions.php ─────

var PHP_FILE = '<?php\n'
  + '// Generated by PlayBrick setup — do not edit manually.\n'
  + '// To regenerate: pnpm run setup\n'
  + ENQUEUE_HOOK;

var includesDir = path.join(CHILD_THEME, 'includes');
if (!fs.existsSync(includesDir)) {
  fs.mkdirSync(includesDir, { recursive: true });
}

var phpFile = path.join(includesDir, 'playbrick-enqueue.php');
fs.writeFileSync(phpFile, PHP_FILE);
console.log('✓  Written: ' + path.relative(ROOT, phpFile));

// Patch functions.php
var functionsPath = path.join(CHILD_THEME, 'functions.php');
var requireLine   = "require_once get_stylesheet_directory() . '/includes/playbrick-enqueue.php';";

if (!fs.existsSync(functionsPath)) {
  console.warn('Warning: functions.php not found at ' + functionsPath);
  console.warn('         Add this line manually:\n         ' + requireLine);
  done();
  return;
}

var functionsContent = fs.readFileSync(functionsPath, 'utf8');

if (functionsContent.includes('playbrick-enqueue.php')) {
  console.log('✓  functions.php already loads playbrick-enqueue.php — no changes.');
} else {
  var trimmedFn = functionsContent.trimEnd();
  if (trimmedFn.endsWith('?>')) {
    functionsContent = trimmedFn.slice(0, -2).trimEnd() + '\n\n' + requireLine + '\n';
  } else {
    functionsContent = trimmedFn + '\n\n' + requireLine + '\n';
  }
  fs.writeFileSync(functionsPath, functionsContent);
  console.log('✓  Patched: ' + path.relative(ROOT, functionsPath));
}

done();

// ── helpers ───────────────────────────────────────────────────────────────────

function done() {
  console.log('\nSetup complete.');
  console.log('  Dev mode  (default) — no wp-config.php change needed.');
  console.log("  Prod mode           — add to wp-config.php:  define('PLAYBRICK_ENV', 'prod');");
}
