#!/usr/bin/env node
'use strict';

var fs   = require('fs');
var path = require('path');

var ROOT       = __dirname;
var configPath = path.join(ROOT, 'playbrick.config.js');

if (!fs.existsSync(configPath)) {
  console.error('Error: playbrick.config.js not found.');
  console.error('       Copy playbrick.config.js.example → playbrick.config.js and fill in the values.');
  process.exit(1);
}

var config = require(configPath);

if (!config.childTheme) {
  console.error('Error: playbrick.config.js is missing "childTheme".');
  console.error('       Add: childTheme: \'../wp-content/themes/my-child-theme\'');
  process.exit(1);
}

var CHILD_THEME = path.resolve(ROOT, config.childTheme);

// Derive the uploads sub-path from outDir (e.g. "uploads/assets" → "assets").
var assetsSubdir = 'assets';
if (config.outDir) {
  var normalized = config.outDir.replace(/\\/g, '/');
  var match = normalized.match(/wp-content\/uploads\/(.+?)\/?\s*$/);
  if (match) {
    assetsSubdir = match[1];
  } else {
    console.warn('Warning: outDir does not look like a wp-content/uploads/* path.');
    console.warn('         Edit includes/playbrick-enqueue.php manually after setup.');
  }
}

// ── Generate enqueue PHP ──────────────────────────────────────────────────────

var PHP = '<?php\n'
  + '// Generated by PlayBrick setup — do not edit manually.\n'
  + '// To regenerate: pnpm run setup\n'
  + '\n'
  + 'function playbrick_enqueue() {\n'
  + "    $is_dev = ! defined( 'PLAYBRICK_ENV' ) || PLAYBRICK_ENV === 'dev';\n"
  + '\n'
  + '    if ( $is_dev ) {\n'
  + '        // Development: serve directly from playbrick/ — no build step needed.\n'
  + "        $base = get_home_url() . '/playbrick';\n"
  + "        wp_enqueue_style( 'playbrick', $base . '/dev.css', [], null );\n"
  + "        wp_enqueue_script( 'playbrick', $base . '/dev.js', [], null, true );\n"
  + '    } else {\n'
  + '        // Production: serve minified output from `pnpm run build`.\n'
  + '        $upload = wp_upload_dir();\n'
  + "        $base   = $upload['baseurl'] . '/" + assetsSubdir + "';\n"
  + "        wp_enqueue_style( 'playbrick', $base . '/style.min.css', [], null );\n"
  + "        wp_enqueue_script( 'playbrick', $base . '/script.min.js', [], null, true );\n"
  + '    }\n'
  + '}\n'
  + "add_action( 'wp_enqueue_scripts', 'playbrick_enqueue' );\n";

// ── Write to child theme ──────────────────────────────────────────────────────

var includesDir = path.join(CHILD_THEME, 'includes');
if (!fs.existsSync(includesDir)) {
  fs.mkdirSync(includesDir, { recursive: true });
}

var phpFile = path.join(includesDir, 'playbrick-enqueue.php');
fs.writeFileSync(phpFile, PHP);
console.log('✓  Written: ' + path.relative(ROOT, phpFile));

// ── Patch functions.php ───────────────────────────────────────────────────────

var functionsPath = path.join(CHILD_THEME, 'functions.php');
var requireLine   = "require_once get_stylesheet_directory() . '/includes/playbrick-enqueue.php';";

if (!fs.existsSync(functionsPath)) {
  console.warn('Warning: functions.php not found at ' + functionsPath);
  console.warn('         Add this line manually:\n         ' + requireLine);
  process.exit(0);
}

var content = fs.readFileSync(functionsPath, 'utf8');

if (content.includes('playbrick-enqueue.php')) {
  console.log('✓  functions.php already loads playbrick-enqueue.php — no changes.');
} else {
  // Append before closing ?> if present, otherwise just append.
  var trimmed = content.trimEnd();
  if (trimmed.endsWith('?>')) {
    content = trimmed.slice(0, -2).trimEnd() + '\n\n' + requireLine + '\n';
  } else {
    content = trimmed + '\n\n' + requireLine + '\n';
  }
  fs.writeFileSync(functionsPath, content);
  console.log('✓  Patched: ' + path.relative(ROOT, functionsPath));
}

console.log('\nSetup complete.');
console.log('  Dev mode  (default) — no wp-config.php change needed.');
console.log("  Prod mode           — add to wp-config.php:  define('PLAYBRICK_ENV', 'prod');");
