<?php
namespace PlayBrick\Tests;

use PHPUnit\Framework\TestCase;

class BricksSourceTest extends TestCase {

	private function rmdir( string $dir ): void {
		if ( ! is_dir( $dir ) ) {
			return;
		}

		$items = new \RecursiveIteratorIterator(
			new \RecursiveDirectoryIterator( $dir, \RecursiveDirectoryIterator::SKIP_DOTS ),
			\RecursiveIteratorIterator::CHILD_FIRST
		);

		foreach ( $items as $item ) {
			$path = $item->getPathname();
			if ( $item->isDir() ) {
				rmdir( $path );
			} else {
				unlink( $path );
			}
		}

		rmdir( $dir );
	}

	protected function tearDown(): void {
		$this->rmdir( sys_get_temp_dir() . '/playbrick-bricks-source' );
		parent::tearDown();
	}

	public function test_extracts_local_global_and_attribute_classes_from_bricks_data(): void {
		$data = [
			[
				'settings' => [
					'_cssClasses'       => 'bg-red-500 md:hover:text-white',
					'_cssGlobalClasses' => [ 'abc123' ],
					'_attributes'       => [
						[ 'name' => 'class', 'value' => 'custom-attr-class px-4' ],
					],
				],
			],
		];

		$classes = playbrick_extract_classes_from_bricks_data( $data, [ 'abc123' => 'eq-button' ] );

		$this->assertSame(
			[ 'bg-red-500', 'custom-attr-class', 'eq-button', 'md:hover:text-white', 'px-4' ],
			$classes
		);
	}

	public function test_write_bricks_tailwind_source_creates_generated_html(): void {
		$playground = sys_get_temp_dir() . '/playbrick-bricks-source/playground';

		$path = playbrick_write_bricks_tailwind_source( $playground, [ 'px-4', 'bg-red-500', 'px-4', 'bad<class' ] );

		$this->assertSame( $playground . '/.playbrick/bricks-sources.html', $path );
		$this->assertFileExists( $path );

		$contents = file_get_contents( $path );
		$this->assertStringContainsString( 'Generated by PlayBrick', $contents );
		$this->assertStringContainsString( 'class="bg-red-500 px-4"', $contents );
		$this->assertStringNotContainsString( 'bad<class', $contents );
	}
}
