<?php
namespace PlayBrick\Tests;

use PHPUnit\Framework\TestCase;

class BricksSourceTest extends TestCase {

	private function rmdir( string $dir ): void {
		if ( ! is_dir( $dir ) ) {
			return;
		}

		$items = new \RecursiveIteratorIterator(
			new \RecursiveDirectoryIterator( $dir, \RecursiveDirectoryIterator::SKIP_DOTS ),
			\RecursiveIteratorIterator::CHILD_FIRST
		);

		foreach ( $items as $item ) {
			$path = $item->getPathname();
			if ( $item->isDir() ) {
				rmdir( $path );
			} else {
				unlink( $path );
			}
		}

		rmdir( $dir );
	}

	protected function tearDown(): void {
		$this->rmdir( sys_get_temp_dir() . '/playbrick-bricks-source' );
		parent::tearDown();
	}

	public function test_extracts_local_global_and_attribute_classes_from_bricks_data(): void {
		$data = [
			[
				'settings' => [
					'_cssClasses'       => 'bg-red-500 md:hover:text-white',
					'_cssGlobalClasses' => [ 'abc123' ],
					'_attributes'       => [
						[ 'name' => 'class', 'value' => 'custom-attr-class px-4' ],
					],
				],
			],
		];

		$classes = playbrick_extract_classes_from_bricks_data( $data, [ 'abc123' => 'eq-button' ] );

		$this->assertSame(
			[ 'bg-red-500', 'custom-attr-class', 'eq-button', 'md:hover:text-white', 'px-4' ],
			$classes
		);
	}

	public function test_write_bricks_tailwind_source_creates_generated_html(): void {
		$playground = sys_get_temp_dir() . '/playbrick-bricks-source/playground';

		$path = playbrick_write_bricks_tailwind_source( $playground, [ 'px-4', 'bg-red-500', 'px-4', '[&>*]:mt-4', "before:content-['']", "bad class" ], '.t-c1 { @apply bg-red-500; }' );

		$this->assertSame( $playground . '/.playbrick/bricks-sources.html', $path );
		$this->assertFileExists( $path );
		$this->assertFileExists( $playground . '/.playbrick/bricks-sources.txt' );
		$this->assertFileExists( $playground . '/.playbrick/bricks-custom.css' );

		$contents = file_get_contents( $path );
		$this->assertStringContainsString( 'Generated by PlayBrick', $contents );
		$this->assertStringContainsString( 'bg-red-500', $contents );
		$this->assertStringContainsString( '[&amp;&gt;*]:mt-4', $contents );

		$raw_contents = file_get_contents( $playground . '/.playbrick/bricks-sources.txt' );
		$this->assertStringContainsString( '[&>*]:mt-4', $raw_contents );
		$this->assertStringContainsString( "before:content-['']", $raw_contents );
		$this->assertStringNotContainsString( 'bad class', $raw_contents );

		$custom_css = file_get_contents( $playground . '/.playbrick/bricks-custom.css' );
		$this->assertStringContainsString( '.t-c1 { @apply bg-red-500; }', $custom_css );
	}

	public function test_normalizes_bare_custom_css_for_tailwind_apply(): void {
		$css = playbrick_normalize_tailwind_custom_css_block( "@apply bg-red-500\ncolor: white;", '.t-c1' );

		$this->assertStringContainsString( '.t-c1 {', $css );
		$this->assertStringContainsString( '@apply bg-red-500;', $css );
		$this->assertStringContainsString( 'color: white;', $css );
	}

	public function test_extracts_tailwind_apply_classes_from_custom_css(): void {
		$classes = playbrick_extract_tailwind_apply_classes( ".t-c3 {\n  @apply text-white text-5xl font-bold;\n}" );

		$this->assertSame( [ 'font-bold', 'text-5xl', 'text-white' ], $classes );
	}

	public function test_builds_theme_css_from_bricks_color_palette(): void {
		$palette = [
			[
				'id'     => 'pal1',
				'name'   => 'Main',
				'colors' => [
					[ 'id' => 'abc123', 'name' => 'Brand Amber', 'hex' => '#ffc107' ],
					[ 'id' => 'def456', 'name' => 'White', 'hex' => '#ffffff' ],
				],
			],
		];

		$css = playbrick_build_bricks_theme_css( $palette );

		$this->assertStringContainsString( 'Auto-generated by PlayBrick', $css );
		$this->assertStringContainsString( '@theme inline {', $css );
		$this->assertStringContainsString( '--color-brand-amber: var(--bricks-color-abc123);', $css );
		$this->assertStringContainsString( '--color-white: var(--bricks-color-def456);', $css );
	}

	public function test_builds_theme_css_with_header_only_for_empty_palette(): void {
		$css = playbrick_build_bricks_theme_css( [] );

		$this->assertStringContainsString( 'Auto-generated by PlayBrick', $css );
		$this->assertStringContainsString( 'No Bricks color palette found', $css );
		$this->assertStringNotContainsString( '@theme', $css );
	}

	public function test_theme_color_slug_handles_accents_and_whitespace(): void {
		$palette = [
			[
				'id'     => 'pal1',
				'name'   => 'Main',
				'colors' => [
					[ 'id' => 'abc123', 'name' => 'Ámbar', 'hex' => '#ffc107' ],
					[ 'id' => 'def456', 'name' => '  Verde   Oscuro  ', 'hex' => '#1b5e20' ],
				],
			],
		];

		$css = playbrick_build_bricks_theme_css( $palette );

		$this->assertStringContainsString( '--color-ambar: var(--bricks-color-abc123);', $css );
		$this->assertStringContainsString( '--color-verde-oscuro: var(--bricks-color-def456);', $css );
	}

	public function test_theme_color_slug_falls_back_to_raw_var_and_id(): void {
		// Default-palette style color: no name, raw CSS var defines slug and var name.
		$css = playbrick_build_bricks_theme_css(
			[
				[
					'id'     => 'pal1',
					'name'   => 'Default',
					'colors' => [
						[ 'id' => 'x1y2z3', 'light' => '#ffc107', 'raw' => 'var(--bricks-color-amber)' ],
					],
				],
			]
		);

		$this->assertStringContainsString( '--color-amber: var(--bricks-color-amber);', $css );

		// No name and no raw var: fall back to the color id.
		$css = playbrick_build_bricks_theme_css(
			[
				[
					'id'     => 'pal1',
					'name'   => 'Main',
					'colors' => [
						[ 'id' => 'q7w8e9', 'hex' => '#000000' ],
					],
				],
			]
		);

		$this->assertStringContainsString( '--color-q7w8e9: var(--bricks-color-q7w8e9);', $css );
	}

	public function test_theme_color_slug_collisions_get_numeric_suffixes(): void {
		$palette = [
			[
				'id'     => 'pal1',
				'name'   => 'Main',
				'colors' => [
					[ 'id' => 'aaa111', 'name' => 'Brand Amber', 'hex' => '#111111' ],
					[ 'id' => 'bbb222', 'name' => 'brand amber', 'hex' => '#222222' ],
					[ 'id' => 'ccc333', 'name' => 'Brand  Amber', 'hex' => '#333333' ],
				],
			],
		];

		$css = playbrick_build_bricks_theme_css( $palette );

		$this->assertStringContainsString( '--color-brand-amber: var(--bricks-color-aaa111);', $css );
		$this->assertStringContainsString( '--color-brand-amber-2: var(--bricks-color-bbb222);', $css );
		$this->assertStringContainsString( '--color-brand-amber-3: var(--bricks-color-ccc333);', $css );
	}

	public function test_write_bricks_tailwind_source_creates_theme_css(): void {
		$playground = sys_get_temp_dir() . '/playbrick-bricks-source/playground';
		$theme_css  = playbrick_build_bricks_theme_css(
			[
				[
					'id'     => 'pal1',
					'name'   => 'Main',
					'colors' => [
						[ 'id' => 'abc123', 'name' => 'Brand Amber', 'hex' => '#ffc107' ],
					],
				],
			]
		);

		playbrick_write_bricks_tailwind_source( $playground, [ 'px-4' ], '', $theme_css );

		$theme_css_path = $playground . '/.playbrick/bricks-theme.css';
		$this->assertFileExists( $theme_css_path );

		$contents = file_get_contents( $theme_css_path );
		$this->assertStringContainsString( '@theme inline {', $contents );
		$this->assertStringContainsString( '--color-brand-amber: var(--bricks-color-abc123);', $contents );
	}

	public function test_write_bricks_tailwind_source_updates_theme_css_when_palette_changes(): void {
		$playground = sys_get_temp_dir() . '/playbrick-bricks-source/playground';

		$theme_css_v1 = playbrick_build_bricks_theme_css(
			[
				[
					'id'     => 'pal1',
					'name'   => 'Main',
					'colors' => [
						[ 'id' => 'abc123', 'name' => 'Brand Amber', 'hex' => '#ffc107' ],
					],
				],
			]
		);

		playbrick_write_bricks_tailwind_source( $playground, [ 'px-4' ], '', $theme_css_v1 );

		$theme_css_path = $playground . '/.playbrick/bricks-theme.css';
		$this->assertStringContainsString( '--color-brand-amber', file_get_contents( $theme_css_path ) );

		// Same classes but a changed palette: the early-return guard must not skip the rewrite.
		$theme_css_v2 = playbrick_build_bricks_theme_css(
			[
				[
					'id'     => 'pal1',
					'name'   => 'Main',
					'colors' => [
						[ 'id' => 'def456', 'name' => 'Ocean Blue', 'hex' => '#2196f3' ],
					],
				],
			]
		);

		playbrick_write_bricks_tailwind_source( $playground, [ 'px-4' ], '', $theme_css_v2 );

		$contents = file_get_contents( $theme_css_path );
		$this->assertStringContainsString( '--color-ocean-blue: var(--bricks-color-def456);', $contents );
		$this->assertStringNotContainsString( '--color-brand-amber', $contents );
	}

	public function test_builds_theme_css_skipping_malformed_palette_entries(): void {
		$palette = [
			'not-a-palette-array',
			[ 'id' => 'pal1', 'name' => 'Broken', 'colors' => 'not-an-array' ],
			[
				'id'     => 'pal2',
				'name'   => 'Main',
				'colors' => [
					'not-a-color-array',
					[ 'hex' => '#000000' ], // No id, name or raw: nothing to reference.
					[ 'id' => 'abc123', 'name' => 'Brand Amber', 'hex' => '#ffc107' ],
				],
			],
		];

		$css = playbrick_build_bricks_theme_css( $palette );

		$this->assertStringContainsString( '--color-brand-amber: var(--bricks-color-abc123);', $css );
		$this->assertSame( 1, substr_count( $css, '--color-' ) );
		$this->assertStringNotContainsString( '#000000', $css );
	}
}
