<?php
namespace PlayBrick\Tests;

use PHPUnit\Framework\TestCase;

class BricksSourceTest extends TestCase {

	private function rmdir( string $dir ): void {
		if ( ! is_dir( $dir ) ) {
			return;
		}

		$items = new \RecursiveIteratorIterator(
			new \RecursiveDirectoryIterator( $dir, \RecursiveDirectoryIterator::SKIP_DOTS ),
			\RecursiveIteratorIterator::CHILD_FIRST
		);

		foreach ( $items as $item ) {
			$path = $item->getPathname();
			if ( $item->isDir() ) {
				rmdir( $path );
			} else {
				unlink( $path );
			}
		}

		rmdir( $dir );
	}

	protected function tearDown(): void {
		$this->rmdir( sys_get_temp_dir() . '/playbrick-bricks-source' );
		parent::tearDown();
	}

	public function test_extracts_local_global_and_attribute_classes_from_bricks_data(): void {
		$data = [
			[
				'settings' => [
					'_cssClasses'       => 'bg-red-500 md:hover:text-white',
					'_cssGlobalClasses' => [ 'abc123' ],
					'_attributes'       => [
						[ 'name' => 'class', 'value' => 'custom-attr-class px-4' ],
					],
				],
			],
		];

		$classes = playbrick_extract_classes_from_bricks_data( $data, [ 'abc123' => 'eq-button' ] );

		$this->assertSame(
			[ 'bg-red-500', 'custom-attr-class', 'eq-button', 'md:hover:text-white', 'px-4' ],
			$classes
		);
	}

	public function test_write_bricks_tailwind_source_creates_generated_html(): void {
		$playground = sys_get_temp_dir() . '/playbrick-bricks-source/playground';

		$path = playbrick_write_bricks_tailwind_source( $playground, [ 'px-4', 'bg-red-500', 'px-4', '[&>*]:mt-4', "before:content-['']", "bad class" ], '.t-c1 { @apply bg-red-500; }' );

		$this->assertSame( $playground . '/.playbrick/bricks-sources.html', $path );
		$this->assertFileExists( $path );
		$this->assertFileExists( $playground . '/.playbrick/bricks-sources.txt' );
		$this->assertFileExists( $playground . '/.playbrick/bricks-custom.css' );

		$contents = file_get_contents( $path );
		$this->assertStringContainsString( 'Generated by PlayBrick', $contents );
		$this->assertStringContainsString( 'bg-red-500', $contents );
		$this->assertStringContainsString( '[&amp;&gt;*]:mt-4', $contents );

		$raw_contents = file_get_contents( $playground . '/.playbrick/bricks-sources.txt' );
		$this->assertStringContainsString( '[&>*]:mt-4', $raw_contents );
		$this->assertStringContainsString( "before:content-['']", $raw_contents );
		$this->assertStringNotContainsString( 'bad class', $raw_contents );

		$custom_css = file_get_contents( $playground . '/.playbrick/bricks-custom.css' );
		$this->assertStringContainsString( '.t-c1 { @apply bg-red-500; }', $custom_css );
	}

	public function test_normalizes_bare_custom_css_for_tailwind_apply(): void {
		$css = playbrick_normalize_tailwind_custom_css_block( "@apply bg-red-500\ncolor: white;", '.t-c1' );

		$this->assertStringContainsString( '.t-c1 {', $css );
		$this->assertStringContainsString( '@apply bg-red-500;', $css );
		$this->assertStringContainsString( 'color: white;', $css );
	}

	public function test_wraps_mobile_portrait_custom_css_in_default_bricks_media_query(): void {
		$css = playbrick_normalize_tailwind_custom_css_block( '@apply text-xs;', '.font-title', '_cssCustom:mobile_portrait' );

		$this->assertStringContainsString( '@media (max-width: 478px) {', $css );
		$this->assertStringContainsString( ".font-title {\n  @apply text-xs;\n}", $css );
		$this->assertLessThan( strpos( $css, '.font-title {' ), strpos( $css, '@media (max-width: 478px) {' ) );
	}

	public function test_leaves_default_desktop_custom_css_unwrapped(): void {
		$css = playbrick_normalize_tailwind_custom_css_block( '@apply text-5xl;', '.font-title', '_cssCustom' );

		$this->assertStringContainsString( ".font-title {\n  @apply text-5xl;\n}", $css );
		$this->assertStringNotContainsString( '@media', $css );
	}

	public function test_skips_unknown_breakpoint_instead_of_leaking_custom_css(): void {
		$css = playbrick_normalize_tailwind_custom_css_block( '@apply text-xs;', '.font-title', '_cssCustom:unknown' );

		$this->assertStringContainsString( 'Skipped unresolved Bricks breakpoint: _cssCustom:unknown', $css );
		$this->assertStringNotContainsString( '@apply text-xs', $css );
	}

	public function test_extracts_tailwind_apply_classes_from_custom_css(): void {
		$classes = playbrick_extract_tailwind_apply_classes( ".t-c3 {\n  @apply text-white text-5xl font-bold;\n}" );

		$this->assertSame( [ 'font-bold', 'text-5xl', 'text-white' ], $classes );
	}

	public function test_collects_element_custom_css_from_bricks_content_rows(): void {
		$data = [
			[ 'id' => 'abc123', 'settings' => [ '_cssCustom' => '@apply grid gap-5;' ] ],
			[ 'id' => 'invalid', 'settings' => [ '_cssCustom' => '@apply hidden;' ] ],
		];

		$reflection = new \ReflectionFunction( 'playbrick_extract_tailwind_custom_css_from_bricks_data' );
		$css = $reflection->invoke( $data );

		$this->assertCount( 1, $css );
		$this->assertStringContainsString( '#brxe-abc123 {', $css[0] );
		$this->assertStringContainsString( '@apply grid gap-5;', $css[0] );
		$this->assertStringNotContainsString( 'hidden', $css[0] );
	}

	public function test_builds_theme_css_from_bricks_color_palette(): void {
		$palette = [
			[
				'id'     => 'pal1',
				'name'   => 'Main',
				'colors' => [
					[ 'id' => 'abc123', 'name' => 'Brand Amber', 'hex' => '#ffc107' ],
					[ 'id' => 'def456', 'name' => 'White', 'hex' => '#ffffff' ],
				],
			],
		];

		$css = playbrick_build_bricks_theme_css( $palette );

		$this->assertStringContainsString( 'Auto-generated by PlayBrick', $css );
		$this->assertStringContainsString( 'Bricks Style Manager variables / palette', $css );
		$this->assertStringContainsString( '@theme inline {', $css );
		$this->assertStringContainsString( '--color-brand-amber: var(--bricks-color-abc123, #ffc107);', $css );
		$this->assertStringContainsString( '--color-white: var(--bricks-color-def456, #ffffff);', $css );
	}

	public function test_builds_theme_css_with_header_only_for_empty_theme_sources(): void {
		$css = playbrick_build_bricks_theme_css( [] );

		$this->assertStringContainsString( 'Auto-generated by PlayBrick', $css );
		$this->assertStringContainsString( 'No Bricks Style Manager variables or color palette found', $css );
		$this->assertStringNotContainsString( '@theme', $css );
	}

	public function test_builds_theme_css_from_bricks_global_variables(): void {
		$variables = [
			[ 'id' => 'space1', 'name' => 'space-m', 'value' => 'clamp(1rem, 2vw, 2rem)', 'category' => 'Spacing' ],
			[ 'id' => 'text1', 'name' => 'text-xl', 'value' => 'clamp(1.5rem, 3vw, 2rem)', 'category' => 'Typography' ],
			[ 'id' => 'color1', 'name' => 'color-primary', 'value' => '#0f766e', 'category' => 'Colors' ],
			[ 'id' => 'radius1', 'name' => 'card-radius', 'value' => '20px', 'category' => 'Radii' ],
			[ 'id' => 'shadow1', 'name' => 'shadow-card', 'value' => '0 12px 30px rgb(0 0 0 / 0.12)', 'category' => 'Shadows' ],
			[ 'id' => 'leading1', 'name' => 'leading-normal', 'value' => '1.5', 'category' => 'Typography' ],
		];

		$css = playbrick_build_bricks_theme_css( [], $variables );

		$this->assertStringContainsString( '@theme inline {', $css );
		$this->assertStringContainsString( '--spacing-m: var(--space-m, clamp(1rem, 2vw, 2rem));', $css );
		$this->assertStringContainsString( '--text-xl: clamp(1.5rem, 3vw, 2rem);', $css );
		$this->assertStringContainsString( '--color-primary: #0f766e;', $css );
		$this->assertStringContainsString( '--radius-card: var(--card-radius, 20px);', $css );
		$this->assertStringContainsString( '--shadow-card: 0 12px 30px rgb(0 0 0 / 0.12);', $css );
		$this->assertStringContainsString( '--leading-normal: 1.5;', $css );
	}

	public function test_generates_grid_utilities_that_reference_bricks_variables(): void {
		$variables = [
			[ 'id' => 'columns1', 'name' => 'grid-template-columns-dashboard', 'value' => '16rem minmax(0, 1fr)' ],
			[ 'id' => 'rows1', 'name' => 'grid-template-rows-layout', 'value' => 'auto minmax(0, 1fr) auto' ],
			[ 'id' => 'invalid1', 'name' => 'grid-template-columns-', 'value' => '1fr' ],
			[ 'id' => 'other1', 'name' => 'grid-template-areas-dashboard', 'value' => '"nav main"' ],
		];

		$classes = playbrick_collect_bricks_global_variable_grid_utility_classes( $variables );
		$css     = playbrick_build_bricks_theme_css( [], $variables );
		$playground = sys_get_temp_dir() . '/playbrick-bricks-source/playground';
		$path = playbrick_write_bricks_tailwind_source( $playground, $classes, '', $css );

		$this->assertSame( [ 'grid-cols-dashboard', 'grid-rows-layout' ], $classes );
		$this->assertStringContainsString( '--grid-template-columns-dashboard: var(--grid-template-columns-dashboard);', $css );
		$this->assertStringContainsString( '--grid-template-rows-layout: var(--grid-template-rows-layout);', $css );
		$this->assertStringNotContainsString( 'grid-template-areas-dashboard', $css );
		$this->assertStringContainsString( 'grid-cols-dashboard grid-rows-layout', file_get_contents( $path ) );
	}

	public function test_builds_theme_css_skipping_malformed_global_variables(): void {
		$css = playbrick_build_bricks_theme_css(
			[],
			[
				'not-a-variable-array',
				[ 'name' => '', 'value' => '1rem' ],
				[ 'name' => 'space-empty', 'value' => '' ],
				[ 'name' => '-space-m', 'value' => '1rem' ],
				[ 'name' => 'space m', 'value' => '1rem' ],
				[ 'name' => 'bad:value', 'value' => '1rem' ],
				[ 'name' => 'text-bad', 'value' => '1rem; color: red' ],
				[ 'name' => 'unsupported-token', 'value' => '1rem' ],
				[ 'name' => 'space-m', 'value' => '1rem' ],
			]
		);

		$this->assertStringContainsString( '--spacing-m: var(--space-m, 1rem);', $css );
		$this->assertSame( 1, substr_count( $css, '--spacing-' ) );
		$this->assertStringNotContainsString( '--unsupported-token', $css );
		$this->assertStringNotContainsString( '--bad:value', $css );
		$this->assertStringNotContainsString( 'color: red', $css );
	}

	public function test_theme_token_collisions_between_palette_and_global_variables_get_numeric_suffixes(): void {
		$css = playbrick_build_bricks_theme_css(
			[
				[
					'id'     => 'pal1',
					'name'   => 'Main',
					'colors' => [
						[ 'id' => 'abc123', 'name' => 'Primary', 'hex' => '#111111' ],
					],
				],
			],
			[
				[ 'id' => 'color1', 'name' => 'color-primary', 'value' => '#222222' ],
			]
		);

		$this->assertStringContainsString( '--color-primary: var(--bricks-color-abc123, #111111);', $css );
		$this->assertStringContainsString( '--color-primary-2: #222222;', $css );
	}

	public function test_theme_token_dedupes_same_token_and_value(): void {
		$css = playbrick_build_bricks_theme_css(
			[],
			[
				[ 'id' => 'color1', 'name' => 'color-primary', 'value' => '#222222' ],
				[ 'id' => 'color2', 'name' => 'color-primary', 'value' => '#222222' ],
			]
		);

		$this->assertSame( 1, substr_count( $css, '--color-primary: #222222;' ) );
		$this->assertStringNotContainsString( '--color-primary-2', $css );
	}

	public function test_theme_color_slug_handles_accents_and_whitespace(): void {
		$palette = [
			[
				'id'     => 'pal1',
				'name'   => 'Main',
				'colors' => [
					[ 'id' => 'abc123', 'name' => 'Ámbar', 'hex' => '#ffc107' ],
					[ 'id' => 'def456', 'name' => '  Verde   Oscuro  ', 'hex' => '#1b5e20' ],
				],
			],
		];

		$css = playbrick_build_bricks_theme_css( $palette );

		$this->assertStringContainsString( '--color-ambar: var(--bricks-color-abc123, #ffc107);', $css );
		$this->assertStringContainsString( '--color-verde-oscuro: var(--bricks-color-def456, #1b5e20);', $css );
	}

	public function test_theme_color_slug_falls_back_to_raw_var_and_id(): void {
		// Default-palette style color: no name, raw CSS var defines slug and var name.
		$css = playbrick_build_bricks_theme_css(
			[
				[
					'id'     => 'pal1',
					'name'   => 'Default',
					'colors' => [
						[ 'id' => 'x1y2z3', 'light' => '#ffc107', 'raw' => 'var(--bricks-color-amber)' ],
					],
				],
			]
		);

		$this->assertStringContainsString( '--color-amber: var(--bricks-color-amber, #ffc107);', $css );

		// No name and no raw var: fall back to the color id.
		$css = playbrick_build_bricks_theme_css(
			[
				[
					'id'     => 'pal1',
					'name'   => 'Main',
					'colors' => [
						[ 'id' => 'q7w8e9', 'hex' => '#000000' ],
					],
				],
			]
		);

		$this->assertStringContainsString( '--color-q7w8e9: var(--bricks-color-q7w8e9, #000000);', $css );
	}

	public function test_theme_color_fallback_prefers_safe_light_then_hex(): void {
		$css = playbrick_build_bricks_theme_css(
			[
				[
					'colors' => [
						[ 'id' => 'light1', 'name' => 'Light', 'light' => '#3A8340', 'hex' => '#000000' ],
						[ 'id' => 'hex1', 'name' => 'Hex', 'light' => 'red; color: black', 'hex' => '#f5f5f5' ],
						[ 'id' => 'none1', 'name' => 'No fallback', 'light' => 'red; color: black' ],
					],
				],
			]
		);

		$this->assertStringContainsString( '--color-light: var(--bricks-color-light1, #3A8340);', $css );
		$this->assertStringContainsString( '--color-hex: var(--bricks-color-hex1, #f5f5f5);', $css );
		$this->assertStringContainsString( '--color-no-fallback: var(--bricks-color-none1);', $css );
		$this->assertStringNotContainsString( 'color: black', $css );
	}

	public function test_theme_color_slug_collisions_get_numeric_suffixes(): void {
		$palette = [
			[
				'id'     => 'pal1',
				'name'   => 'Main',
				'colors' => [
					[ 'id' => 'aaa111', 'name' => 'Brand Amber', 'hex' => '#111111' ],
					[ 'id' => 'bbb222', 'name' => 'brand amber', 'hex' => '#222222' ],
					[ 'id' => 'ccc333', 'name' => 'Brand  Amber', 'hex' => '#333333' ],
				],
			],
		];

		$css = playbrick_build_bricks_theme_css( $palette );

		$this->assertStringContainsString( '--color-brand-amber: var(--bricks-color-aaa111, #111111);', $css );
		$this->assertStringContainsString( '--color-brand-amber-2: var(--bricks-color-bbb222, #222222);', $css );
		$this->assertStringContainsString( '--color-brand-amber-3: var(--bricks-color-ccc333, #333333);', $css );
	}

	public function test_write_bricks_tailwind_source_creates_theme_css(): void {
		$playground = sys_get_temp_dir() . '/playbrick-bricks-source/playground';
		$theme_css  = playbrick_build_bricks_theme_css(
			[
				[
					'id'     => 'pal1',
					'name'   => 'Main',
					'colors' => [
						[ 'id' => 'abc123', 'name' => 'Brand Amber', 'hex' => '#ffc107' ],
					],
				],
			]
		);

		playbrick_write_bricks_tailwind_source( $playground, [ 'px-4' ], '', $theme_css );

		$theme_css_path = $playground . '/.playbrick/bricks-theme.css';
		$this->assertFileExists( $theme_css_path );

		$contents = file_get_contents( $theme_css_path );
		$this->assertStringContainsString( '@theme inline {', $contents );
		$this->assertStringContainsString( '--color-brand-amber: var(--bricks-color-abc123, #ffc107);', $contents );
	}

	public function test_write_bricks_tailwind_source_updates_theme_css_when_palette_changes(): void {
		$playground = sys_get_temp_dir() . '/playbrick-bricks-source/playground';

		$theme_css_v1 = playbrick_build_bricks_theme_css(
			[
				[
					'id'     => 'pal1',
					'name'   => 'Main',
					'colors' => [
						[ 'id' => 'abc123', 'name' => 'Brand Amber', 'hex' => '#ffc107' ],
					],
				],
			]
		);

		playbrick_write_bricks_tailwind_source( $playground, [ 'px-4' ], '', $theme_css_v1 );

		$theme_css_path = $playground . '/.playbrick/bricks-theme.css';
		$this->assertStringContainsString( '--color-brand-amber', file_get_contents( $theme_css_path ) );

		// Same classes but a changed palette: the early-return guard must not skip the rewrite.
		$theme_css_v2 = playbrick_build_bricks_theme_css(
			[
				[
					'id'     => 'pal1',
					'name'   => 'Main',
					'colors' => [
						[ 'id' => 'def456', 'name' => 'Ocean Blue', 'hex' => '#2196f3' ],
					],
				],
			]
		);

		playbrick_write_bricks_tailwind_source( $playground, [ 'px-4' ], '', $theme_css_v2 );

		$contents = file_get_contents( $theme_css_path );
		$this->assertStringContainsString( '--color-ocean-blue: var(--bricks-color-def456, #2196f3);', $contents );
		$this->assertStringNotContainsString( '--color-brand-amber', $contents );
	}

	public function test_builds_theme_css_skipping_malformed_palette_entries(): void {
		$palette = [
			'not-a-palette-array',
			[ 'id' => 'pal1', 'name' => 'Broken', 'colors' => 'not-an-array' ],
			[
				'id'     => 'pal2',
				'name'   => 'Main',
				'colors' => [
					'not-a-color-array',
					[ 'hex' => '#000000' ], // No id, name or raw: nothing to reference.
					[ 'id' => 'abc123', 'name' => 'Brand Amber', 'hex' => '#ffc107' ],
				],
			],
		];

		$css = playbrick_build_bricks_theme_css( $palette );

		$this->assertStringContainsString( '--color-brand-amber: var(--bricks-color-abc123, #ffc107);', $css );
		$this->assertSame( 1, substr_count( $css, '--color-' ) );
		$this->assertStringNotContainsString( '#000000', $css );
	}
}
