#!/usr/bin/env node

'use strict';

var path        = require('path');
var fs          = require('fs');
var childProcess = require('child_process');
var postcss     = require('postcss');
var tailwindcss = require('@tailwindcss/postcss');
var cssnano     = require('cssnano');
var terser      = require('terser');

var ROOT    = __dirname;
var CSS_IN  = path.join(ROOT, 'dev.css');
var JS_IN   = path.join(ROOT, 'dev.js');

// Load project config (playbrick.config.js) — falls back to dist/
var OUT_DIR = path.join(ROOT, 'dist');
var WP_LOAD_PATH = path.resolve(ROOT, '../wp-load.php');
var configPath = path.join(ROOT, 'playbrick.config.js');
if (fs.existsSync(configPath)) {
  var config = require(configPath);
  if (config.outDir) OUT_DIR = path.resolve(ROOT, config.outDir);
  if (config.wpLoadPath) WP_LOAD_PATH = path.resolve(ROOT, config.wpLoadPath);
}

var CSS_OUT     = path.join(OUT_DIR, 'style.min.css');
var CSS_DEV_OUT = path.join(ROOT, 'dev.built.css');
var JS_OUT      = path.join(OUT_DIR, 'script.min.js');
var BRICKS_SOURCE_OUT = path.join(ROOT, '.playbrick', 'bricks-sources.html');
var BRICKS_RAW_SOURCE_OUT = path.join(ROOT, '.playbrick', 'bricks-sources.txt');
var BRICKS_CUSTOM_CSS_OUT = path.join(ROOT, '.playbrick', 'bricks-custom.css');
var BRICKS_THEME_CSS_OUT = path.join(ROOT, '.playbrick', 'bricks-theme.css');
var TAILWIND_UTILITIES_OUT = path.join(ROOT, '.playbrick', 'tailwind-utilities.json');
var RELOAD_OUT  = path.join(ROOT, 'playbrick.reload.json');

// ── helpers ───────────────────────────────────────────────────────────────────

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function stamp() {
  return new Date().toLocaleTimeString('en', { hour12: false });
}

function readFileIfExists(file) {
  return fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
}

function readBricksSourceSnapshot() {
  return [BRICKS_SOURCE_OUT, BRICKS_RAW_SOURCE_OUT, BRICKS_CUSTOM_CSS_OUT, BRICKS_THEME_CSS_OUT, TAILWIND_UTILITIES_OUT]
    .map(function (file) { return file + '\n' + readFileIfExists(file); })
    .join('\n---\n');
}

function writeFileIfChanged(file, content) {
  if (readFileIfExists(file) === content) return false;

  ensureDir(path.dirname(file));
  fs.writeFileSync(file, content);
  return true;
}

var BRICKS_THEME_CSS_FALLBACK = '/* Auto-generated by PlayBrick. Do not edit — regenerated from the Bricks color palette. */\n' +
  '/* No Bricks color palette found. Save a palette in Bricks (Settings → Color palette), then rebuild. */\n';
var BRICKS_CUSTOM_CSS_FALLBACK = '/* Auto-generated by PlayBrick. Do not edit — regenerated from Bricks custom CSS. */\n' +
  '/* No Bricks custom CSS found. Save custom CSS in Bricks, then rebuild. */\n';

// Self-heal: the PHP export exits 0 silently when WordPress is unavailable, and
// missing generated CSS files hard-fail Tailwind @import resolution.
function ensureGeneratedCssFile(file, fallback, label) {
  if (fs.existsSync(file)) return;

  ensureDir(path.dirname(file));
  fs.writeFileSync(file, fallback);
  console.log('[' + stamp() + '] Created fallback .playbrick/' + label);
}

function ensureGeneratedCssFiles() {
  ensureGeneratedCssFile(BRICKS_THEME_CSS_OUT, BRICKS_THEME_CSS_FALLBACK, 'bricks-theme.css');
  ensureGeneratedCssFile(BRICKS_CUSTOM_CSS_OUT, BRICKS_CUSTOM_CSS_FALLBACK, 'bricks-custom.css');
}

function generateTailwindUtilities() {
  var css = readFileIfExists(BRICKS_THEME_CSS_OUT);
  var prefixes = ['bg', 'text', 'border', 'from', 'via', 'to', 'fill', 'stroke', 'decoration', 'outline', 'ring'];
  var slugs = [];
  var seenSlugs = {};
  var match;
  var tokenRe = /--color-([A-Za-z0-9][A-Za-z0-9_-]*)\s*:/g;

  while ((match = tokenRe.exec(css))) {
    if (seenSlugs[match[1]]) continue;
    seenSlugs[match[1]] = true;
    slugs.push(match[1]);
  }

  var utilities = [];
  var seenUtilities = {};
  slugs.forEach(function (slug) {
    prefixes.forEach(function (prefix) {
      var utility = prefix + '-' + slug;
      if (seenUtilities[utility]) return;
      seenUtilities[utility] = true;
      utilities.push(utility);
    });
  });

  var content = JSON.stringify({ tailwindUtilities: utilities }, null, 2) + '\n';
  if (writeFileIfChanged(TAILWIND_UTILITIES_OUT, content)) {
    console.log('[' + stamp() + '] Tailwind utilities  ->  .playbrick/tailwind-utilities.json  (' + utilities.length + ')');
  }
}

function writeReloadManifest() {
  fs.writeFileSync(RELOAD_OUT, JSON.stringify({ updatedAt: Date.now() }));
}

function exportBricksSource(options) {
  var script = path.join(ROOT, 'export-bricks-source.php');
  if (!fs.existsSync(script)) return;

  var before = readBricksSourceSnapshot();
  var silent = options && options.silent;

  try {
    childProcess.execFileSync('php', [script, WP_LOAD_PATH], { stdio: silent ? 'pipe' : 'inherit' });
  } catch (err) {
    console.warn('[' + stamp() + '] Bricks source export skipped.');
    return false;
  }

  return before !== readBricksSourceSnapshot();
}

// ── CSS build ─────────────────────────────────────────────────────────────────

function buildCSS() {
  exportBricksSource();
  ensureGeneratedCssFiles();
  generateTailwindUtilities();

  var src = fs.readFileSync(CSS_IN, 'utf8');

  return postcss([tailwindcss(), cssnano({ preset: 'default' })])
    .process(src, { from: CSS_IN, to: CSS_OUT })
    .then(function (result) {
      ensureDir(OUT_DIR);
      fs.writeFileSync(CSS_OUT, result.css);
      fs.writeFileSync(CSS_DEV_OUT, result.css);
      var kb = (Buffer.byteLength(result.css, 'utf8') / 1024).toFixed(1);
      console.log('[' + stamp() + '] CSS  →  style.min.css + dev.built.css  (' + kb + ' kB)');
    });
}

// ── JS build ──────────────────────────────────────────────────────────────────

function buildJS() {
  var src = fs.readFileSync(JS_IN, 'utf8');

  return terser.minify(src, {
    compress: { drop_console: false },
    format:   { comments: false }
  }).then(function (result) {
    if (result.error) throw result.error;
    ensureDir(OUT_DIR);
    fs.writeFileSync(JS_OUT, result.code);
    var kb = (Buffer.byteLength(result.code, 'utf8') / 1024).toFixed(1);
    console.log('[' + stamp() + '] JS   →  script.min.js  (' + kb + ' kB)');
  });
}

// ── main ──────────────────────────────────────────────────────────────────────

function build() {
  console.log('[' + stamp() + '] Building…');
  return Promise.all([buildCSS(), buildJS()])
    .then(function () {
      writeReloadManifest();
      console.log('[' + stamp() + '] Done.');
    })
    .catch(function (err) { console.error(err); process.exitCode = 1; });
}

build();

// ── watch mode ────────────────────────────────────────────────────────────────

if (process.argv.includes('--watch')) {
  var chokidar = require('chokidar');

  chokidar
    .watch([
      path.join(ROOT, 'dev.css'),
      path.join(ROOT, 'dev.js'),
      path.join(ROOT, 'bricks/**/*.css'),
      path.join(ROOT, 'bricks/**/*.js'),
      path.join(ROOT, 'export-bricks-source.php')
    ], { ignoreInitial: true })
    .on('change', function (file) {
      console.log('[' + stamp() + '] Changed: ' + path.relative(ROOT, file));
      build();
    });

  setInterval(function () {
    if (exportBricksSource({ silent: true })) {
      console.log('[' + stamp() + '] Changed: .playbrick sources');
      build();
    }
  }, 3000);

  console.log('[' + stamp() + '] Watching… (Ctrl+C to stop)');
  console.log('[' + stamp() + '] Bricks source polling enabled every 3s.');
}
