#!/usr/bin/env node

'use strict';

var path        = require('path');
var fs          = require('fs');
var childProcess = require('child_process');
var postcss     = require('postcss');
var tailwindcss = require('@tailwindcss/postcss');
var cssnano     = require('cssnano');
var terser      = require('terser');

var ROOT    = __dirname;
var CSS_IN  = path.join(ROOT, 'dev.css');
var JS_IN   = path.join(ROOT, 'dev.js');
var IS_WATCH = process.argv.includes('--watch');

// Load project config (playbrick.config.js) — falls back to dist/
var OUT_DIR = path.join(ROOT, 'dist');
var WP_LOAD_PATH = path.resolve(ROOT, '../wp-load.php');
var configPath = path.join(ROOT, 'playbrick.config.js');
if (fs.existsSync(configPath)) {
  var config = require(configPath);
  if (config.outDir) OUT_DIR = path.resolve(ROOT, config.outDir);
  if (config.wpLoadPath) WP_LOAD_PATH = path.resolve(ROOT, config.wpLoadPath);
}

var CSS_OUT     = path.join(OUT_DIR, 'style.min.css');
var CSS_DEV_OUT = path.join(ROOT, 'dev.built.css');
var JS_OUT      = path.join(OUT_DIR, 'script.min.js');
var BRICKS_SOURCE_OUT = path.join(ROOT, '.playbrick', 'bricks-sources.html');
var BRICKS_RAW_SOURCE_OUT = path.join(ROOT, '.playbrick', 'bricks-sources.txt');
var BRICKS_CUSTOM_CSS_OUT = path.join(ROOT, '.playbrick', 'bricks-custom.css');
var BRICKS_THEME_CSS_OUT = path.join(ROOT, '.playbrick', 'bricks-theme.css');
var TAILWIND_UTILITIES_OUT = path.join(ROOT, '.playbrick', 'tailwind-utilities.json');
var RELOAD_OUT  = path.join(ROOT, 'playbrick.reload.json');

// ── helpers ───────────────────────────────────────────────────────────────────

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function stamp() {
  return new Date().toLocaleTimeString('en', { hour12: false });
}

function readFileIfExists(file) {
  return fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
}

function readBricksSourceSnapshot() {
  return [BRICKS_SOURCE_OUT, BRICKS_RAW_SOURCE_OUT, BRICKS_CUSTOM_CSS_OUT, BRICKS_THEME_CSS_OUT, TAILWIND_UTILITIES_OUT]
    .map(function (file) { return file + '\n' + readFileIfExists(file); })
    .join('\n---\n');
}

function writeFileIfChanged(file, content) {
  if (readFileIfExists(file) === content) return false;

  ensureDir(path.dirname(file));
  fs.writeFileSync(file, content);
  return true;
}

var PREFIXES_BY_NAMESPACE = {
  color:   ['bg', 'text', 'border', 'from', 'via', 'to', 'fill', 'stroke', 'decoration', 'outline', 'ring'],
  spacing: ['p', 'px', 'py', 'pt', 'pr', 'pb', 'pl', 'm', 'mx', 'my', 'mt', 'mr', 'mb', 'ml', 'gap'],
  text:    ['text'],
  radius:  ['rounded'],
  shadow:  ['shadow'],
  leading: ['leading'],
  font:    ['font']
};

var NAMESPACE_HINTS = {
  color:   'Bricks → Style Manager → Colors (o tu paleta de color)',
  spacing: 'Bricks → Style Manager → Global Variables',
  text:    'Bricks → Style Manager → Global Variables',
  radius:  'Bricks → Style Manager → Global Variables',
  shadow:  'Bricks → Style Manager → Global Variables',
  leading: 'Bricks → Style Manager → Global Variables',
  font:    'Bricks → Style Manager → Global Variables'
};

var UNKNOWN_UTILITY_RE = /Cannot apply unknown utility class `([^`]+)`/;

// Strips variant prefixes (hover:, md:, after:, etc.) to find the base utility's prefix.
function guessTokenNamespace(className) {
  var bare = className.replace(/^(?:[a-z0-9_-]+:)+/i, '');
  var prefix = bare.split('-')[0];

  for (var namespace in PREFIXES_BY_NAMESPACE) {
    if (PREFIXES_BY_NAMESPACE[namespace].indexOf(prefix) !== -1) return namespace;
  }
  return null;
}

// Translates Tailwind's "unknown utility class" error into a PlayBrick-specific
// hint, since the missing token is almost always a Bricks Style Manager entry
// that hasn't been created yet, not a real Tailwind mistake.
function friendlyBuildError(err) {
  var reason = (err && (err.reason || err.message)) || '';
  var match = UNKNOWN_UTILITY_RE.exec(reason);
  if (!match) return null;

  var className = match[1];
  var namespace = guessTokenNamespace(className);
  var hint = namespace
    ? 'Creá el token correspondiente en ' + NAMESPACE_HINTS[namespace] + ' con el nombre exacto y guardá.'
    : 'Revisá que el nombre esté bien escrito o que el token exista en Bricks Style Manager.';

  return '[' + stamp() + '] ✗ Clase Tailwind desconocida: `' + className + '`\n' +
    '           ' + hint + ' PlayBrick va a recompilar solo apenas lo detecte.';
}

var BRICKS_THEME_CSS_FALLBACK = '/* Auto-generated by PlayBrick. Do not edit — regenerated from Bricks Style Manager variables / palette. */\n' +
  '/* No Bricks Style Manager variables or color palette found. Save variables in Bricks Style Manager or a color palette, then rebuild. */\n';
var BRICKS_CUSTOM_CSS_FALLBACK = '/* Auto-generated by PlayBrick. Do not edit — regenerated from Bricks custom CSS. */\n' +
  '/* No Bricks custom CSS found. Save custom CSS in Bricks, then rebuild. */\n';

// Self-heal: the PHP export exits 0 silently when WordPress is unavailable, and
// missing generated CSS files hard-fail Tailwind @import resolution.
function ensureGeneratedCssFile(file, fallback, label) {
  if (fs.existsSync(file)) return;

  ensureDir(path.dirname(file));
  fs.writeFileSync(file, fallback);
  console.log('[' + stamp() + '] Created fallback .playbrick/' + label);
}

function ensureGeneratedCssFiles() {
  ensureGeneratedCssFile(BRICKS_THEME_CSS_OUT, BRICKS_THEME_CSS_FALLBACK, 'bricks-theme.css');
  ensureGeneratedCssFile(BRICKS_CUSTOM_CSS_OUT, BRICKS_CUSTOM_CSS_FALLBACK, 'bricks-custom.css');
}

function generateTailwindUtilities() {
  var css = readFileIfExists(BRICKS_THEME_CSS_OUT);
  var tokens = [];
  var seenTokens = {};
  var match;
  var tokenRe = /--(color|spacing|text|radius|shadow|leading|font)-([A-Za-z0-9][A-Za-z0-9_-]*)\s*:/g;

  while ((match = tokenRe.exec(css))) {
    var key = match[1] + ':' + match[2];
    if (seenTokens[key]) continue;
    seenTokens[key] = true;
    tokens.push({ namespace: match[1], slug: match[2] });
  }

  var utilities = [];
  var seenUtilities = {};
  tokens.forEach(function (token) {
    PREFIXES_BY_NAMESPACE[token.namespace].forEach(function (prefix) {
      var utility = prefix + '-' + token.slug;
      if (seenUtilities[utility]) return;
      seenUtilities[utility] = true;
      utilities.push(utility);
    });
  });

  var content = JSON.stringify({ tailwindUtilities: utilities }, null, 2) + '\n';
  if (writeFileIfChanged(TAILWIND_UTILITIES_OUT, content)) {
    console.log('[' + stamp() + '] Tailwind utilities  ->  .playbrick/tailwind-utilities.json  (' + utilities.length + ')');
  }
}

function writeReloadManifest() {
  fs.writeFileSync(RELOAD_OUT, JSON.stringify({ updatedAt: Date.now() }));
}

function exportBricksSource(options) {
  var script = path.join(ROOT, 'export-bricks-source.php');
  if (!fs.existsSync(script)) return;

  var before = readBricksSourceSnapshot();
  var silent = options && options.silent;

  try {
    childProcess.execFileSync('php', [script, WP_LOAD_PATH], { stdio: silent ? 'pipe' : 'inherit' });
  } catch (err) {
    console.warn('[' + stamp() + '] Bricks source export skipped.');
    return false;
  }

  return before !== readBricksSourceSnapshot();
}

// ── CSS build ─────────────────────────────────────────────────────────────────

function buildCSS() {
  exportBricksSource();
  ensureGeneratedCssFiles();
  generateTailwindUtilities();

  var src = fs.readFileSync(CSS_IN, 'utf8');

  // Tailwind logs unknown-utility errors to console.error itself before
  // rejecting — buffer that noise so a translatable error (see
  // friendlyBuildError) only shows our one-line hint, not the raw dump.
  var originalConsoleError = console.error;
  var suppressedLogs = [];
  console.error = function () { suppressedLogs.push(arguments); };

  return postcss([tailwindcss(), cssnano({ preset: 'default' })])
    .process(src, { from: CSS_IN, to: CSS_OUT })
    .then(function (result) {
      console.error = originalConsoleError;
      fs.writeFileSync(CSS_DEV_OUT, result.css);
      var kb = (Buffer.byteLength(result.css, 'utf8') / 1024).toFixed(1);
      if (IS_WATCH) {
        console.log('[' + stamp() + '] CSS  →  dev.built.css  (' + kb + ' kB)');
        return;
      }

      ensureDir(OUT_DIR);
      fs.writeFileSync(CSS_OUT, result.css);
      console.log('[' + stamp() + '] CSS  →  style.min.css + dev.built.css  (' + kb + ' kB)');
    }, function (err) {
      console.error = originalConsoleError;
      err.__playbrickSuppressedLogs = suppressedLogs;
      throw err;
    });
}

// ── JS build ──────────────────────────────────────────────────────────────────

function buildJS() {
  var src = fs.readFileSync(JS_IN, 'utf8');

  return terser.minify(src, {
    compress: { drop_console: false },
    format:   { comments: false }
  }).then(function (result) {
    if (result.error) throw result.error;
    if (IS_WATCH) {
      console.log('[' + stamp() + '] JS   →  dev.js  (served raw)');
      return;
    }

    ensureDir(OUT_DIR);
    fs.writeFileSync(JS_OUT, result.code);
    var kb = (Buffer.byteLength(result.code, 'utf8') / 1024).toFixed(1);
    console.log('[' + stamp() + '] JS   →  script.min.js  (' + kb + ' kB)');
  });
}

// ── main ──────────────────────────────────────────────────────────────────────

function build() {
  console.log('[' + stamp() + '] Building…');
  return Promise.all([buildCSS(), buildJS()])
    .then(function () {
      writeReloadManifest();
      console.log('[' + stamp() + '] Done.');
    })
    .catch(function (err) {
      var friendly = friendlyBuildError(err);
      if (friendly) {
        console.error(friendly);
      } else {
        // Unrecognized error — replay whatever Tailwind suppressed so nothing real gets hidden.
        (err && err.__playbrickSuppressedLogs || []).forEach(function (args) {
          console.error.apply(console, args);
        });
        console.error(err);
      }
      // In watch mode, keep the process alive so the next fix (or the 3s
      // Bricks poll) can trigger a fresh build automatically.
      if (!IS_WATCH) process.exitCode = 1;
    });
}

build();

// ── watch mode ────────────────────────────────────────────────────────────────

if (IS_WATCH) {
  var chokidar = require('chokidar');

  chokidar
    .watch([
      path.join(ROOT, 'dev.css'),
      path.join(ROOT, 'dev.js'),
      path.join(ROOT, 'bricks/**/*.css'),
      path.join(ROOT, 'bricks/**/*.js'),
      path.join(ROOT, 'export-bricks-source.php')
    ], { ignoreInitial: true })
    .on('change', function (file) {
      console.log('[' + stamp() + '] Changed: ' + path.relative(ROOT, file));
      build();
    });

  setInterval(function () {
    if (exportBricksSource({ silent: true })) {
      console.log('[' + stamp() + '] Changed: .playbrick sources');
      build();
    }
  }, 3000);

  console.log('[' + stamp() + '] Watching… (Ctrl+C to stop)');
  console.log('[' + stamp() + '] Bricks source polling enabled every 3s.');
}
